image: node:20.11.0-alpine3.18

stages:
  - build
  - package
  - deploy

build_frontend:
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry https://registry.npmjs.org/
    - cd frontend
    - npm ci

build_backend:
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry https://registry.npmjs.org/
    - cd backend
    - npm ci

# kaniko prevents running docker in docker. Equivalent of docker build + docker push
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
package_frontend:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" >/kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/frontend:latest"
  only:
    - main

# kaniko prevents running docker in docker. Equivalent of docker build + docker push
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
package_backend:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - cd backend
    - echo "PORT=5001" > .env
    - echo "DB_URL=$DB_URL" >> .env
    - echo "SECRET=$DB_SECRET" >> .env
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" >/kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"
  only:
    - main


deploy:
  # Utiliser la même image de base que pour Node pour augmenter les chances d'avoir déjà celle-ci sur le runner GitLab.
  image: debian:bullseye-slim
  stage: deploy
  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh $SSH_USER@$VM_IP_ADDRESS "pwd"
    - |
      ssh $SSH_USER@$VM_IP_ADDRESS 'cat >tse/.env' <<EOF
      IMAGE_REPO=${CI_REGISTRY_IMAGE}

      EOF
    - scp deployment/docker-compose.yml $SSH_USER@$VM_IP_ADDRESS:tse
    - ssh $SSH_USER@$VM_IP_ADDRESS 'cd "tse" && docker compose up --detach --remove-orphans'
  only:
    - main

