image: node:20.11.0-alpine3.18

stages:
  - build
  - package
  - deploy

build_frontend:
  stage: build
  script:
    - npm config set proxy null
    - npm config set https-proxy null
    - npm config set registry https://registry.npmjs.org/
    - cd frontend
    - npm ci

# kaniko prevents running docker in docker. Equivalent of docker build + docker push
# https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
package_frontend:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$CI_DEPENDENCY_PROXY_SERVER\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" >/kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/frontend:latest"
  only:
    - main

deploy:
  # Utiliser la même image de base que pour Node pour augmenter les chances d'avoir déjà celle-ci sur le runner GitLab.
  image: debian:bullseye-slim
  stage: deploy
  script:
    - apt-get update && apt-get install --no-install-recommends -y openssh-client
    - eval $(ssh-agent)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -oStrictHostKeyChecking=no $SSH_USER@$VM_IP_ADDRESS "docker ps"
  only:
    - main

